services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: convos-backend
      POSTGRES_USER: xmtp
      POSTGRES_PASSWORD: xmtp
      POSTGRES_PORT: 5432
    ports:
      - "5433:5432"
