services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: convos-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
