#!/usr/bin/env bash
# Local end-to-end auth demo.
# Spec: docs/superpowers/specs/2026-05-11-local-e2e-auth-demo-design.md
# Plan: docs/superpowers/plans/2026-05-11-local-e2e-auth-demo.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Config defaults — override via env.
: "${BASE_URL:=http://localhost:4000}"
: "${PSQL_URL:=postgres://postgres:convos@localhost:5432/postgres?sslmode=disable}"
: "${DEMO_DEVICE_PREFIX:=demo-}"
: "${CONTINUE_ON_FAIL:=0}"
: "${SELF_TEST:=0}"
: "${CONVOS_SERVER_LOG:=}"

export BASE_URL PSQL_URL

# Globals populated as we go.
PASSED_CASES=()
FAILED_CASES=()
SKIPPED_PHASES=()
RUNBOOK="$SCRIPT_DIR/AUTH.md"
TMP=""

# shellcheck source=lib/md.sh
source "$SCRIPT_DIR/lib/md.sh"
# shellcheck source=lib/psql.sh
source "$SCRIPT_DIR/lib/psql.sh"
# shellcheck source=lib/jwt.sh
source "$SCRIPT_DIR/lib/jwt.sh"
# shellcheck source=lib/http.sh
source "$SCRIPT_DIR/lib/http.sh"
# shellcheck source=lib/assert.sh
source "$SCRIPT_DIR/lib/assert.sh"

# --- exit/cleanup -------------------------------------------------------------

write_summary() {
  emit "## Summary"
  emit "Total cases: $((${#PASSED_CASES[@]} + ${#FAILED_CASES[@]}))"
  emit "Pass: ${#PASSED_CASES[@]}"
  emit "Fail: ${#FAILED_CASES[@]}"
  if [[ ${#SKIPPED_PHASES[@]} -gt 0 ]]; then
    emit "Skipped phases: ${SKIPPED_PHASES[*]}"
  fi
  if [[ ${#FAILED_CASES[@]} -gt 0 ]]; then
    emit "**Failures:**"
    for c in "${FAILED_CASES[@]}"; do
      emit "- $c"
    done
  fi
}

on_exit() {
  local code=$?
  write_summary || true
  if [[ -n "$TMP" && -d "$TMP" ]]; then
    rm -rf "$TMP"
  fi
  if [[ ${#FAILED_CASES[@]} -gt 0 || $code -ne 0 ]]; then
    echo "❌ Demo finished with ${#FAILED_CASES[@]} failure(s) (exit $code)." >&2
    exit "${code:-1}"
  fi
  echo "✅ Demo finished. ${#PASSED_CASES[@]} case(s) passed." >&2
  exit 0
}
trap on_exit EXIT

# --- helpers ------------------------------------------------------------------

die() { echo "❌ preflight failed: $1" >&2; exit 1; }
warn() { echo "⚠️  $1" >&2; }

extract_nonce_from_cookie_jar() {
  # Reads cookie jar (Netscape format), extracts the raw nonce (after the dot in <hmac>.<nonce>).
  local jar="$1"
  local cookie_value
  cookie_value=$(awk '$6 == "__Host-convos_nonce" {print $7}' "$jar")
  printf '%s' "${cookie_value##*.}"
}

issue_nonce() {
  # Issues a fresh nonce, returns the cookie jar path on stdout via output arg.
  local jar="$1"
  run_curl "issue fresh nonce" -X POST "$BASE_URL/api/v2/auth/nonce" -c "$jar"
  [[ "$LAST_STATUS" == "200" ]] || { _record_fail "issue_nonce got $LAST_STATUS"; return 1; }
}

sign_and_token() {
  # Args: case_name, expected_status, cookie_jar, deviceId, [extra signer args...].
  # Runs sign-siwe.ts, posts to /auth/token, asserts status.
  local case_name="$1"; shift
  local expected_status="$1"; shift
  local jar="$1"; shift
  local device_id="$1"; shift

  local nonce
  nonce=$(extract_nonce_from_cookie_jar "$jar")

  local siwe_json
  siwe_json=$(bun run "$SCRIPT_DIR/sign-siwe.ts" --nonce "$nonce" "$@")

  local body
  body=$(jq -nc --argjson siwe "$siwe_json" --arg deviceId "$device_id" \
    '{deviceId: $deviceId, siwe: $siwe}')

  run_curl "$case_name" \
    -X POST "$BASE_URL/api/v2/auth/token" \
    -b "$jar" \
    -H "Content-Type: application/json" \
    -d "$body"
  assert_status "$case_name" "$expected_status" "$LAST_STATUS" || return 1
}

start_runbook() {
  cat > "$RUNBOOK" <<EOF
# Local end-to-end auth demo

Generated by \`dev/scripts/run-e2e-demo.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Branch: $(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD) @ $(git -C "$REPO_ROOT" rev-parse --short HEAD).

## ⚠️ Side effects

- Wipes \`Account\`, \`AuthMethod\`, \`AuthNonce\` on every run.
- Flips \`RuntimeConfig.app_attest_enabled\` to \`false\` (demo asserts \`XMTP_ENV != production\` first).
- Modifies \`DeviceRegistration.disabled\` for deviceIds matching \`${DEMO_DEVICE_PREFIX}%\`.

## Prerequisites

- Postgres on localhost:5432 (\`./dev/up\`)
- Migrations applied (\`bun migrate:deploy\`)
- \`bun dev\` running on :4000 with \`SWEEP_INTERVAL_MS=5000\` and stdout tee'd to \`\$CONVOS_SERVER_LOG\`
- \`psql\`, \`jq\`, \`bun\` on PATH

EOF
}

# --- phases -------------------------------------------------------------------

phase0_preflight() {
  emit "## Phase 0 — preflight"

  # Production-safety guard
  if [[ "${XMTP_ENV:-}" == "production" ]]; then
    die "XMTP_ENV=production — refusing to run demo against production"
  fi

  # Postgres
  nc -z localhost 5432 2>/dev/null || die "Postgres not reachable on :5432. Run ./dev/up first."
  _record_pass "Postgres reachable on :5432"

  # Server
  local code
  code=$(curl -sS -o /dev/null -w '%{http_code}' "$BASE_URL/api/v2/auth-check" || echo "000")
  if [[ "$code" != "401" ]]; then
    die "Server not responding correctly on $BASE_URL (got $code, expected 401 for missing token). Run 'bun dev' in another terminal."
  fi
  _record_pass "Server reachable on $BASE_URL (auth-check returned 401)"

  # Tools
  for tool in psql jq bun curl nc; do
    command -v "$tool" >/dev/null || die "$tool not on PATH"
  done
  _record_pass "psql, jq, bun, curl, nc on PATH"

  # Sweep interval warning
  if [[ -z "${SWEEP_INTERVAL_MS:-}" ]]; then
    warn "SWEEP_INTERVAL_MS not exported. Phase 6 will hang 10 min waiting for default sweep."
    warn "Recommended: SWEEP_INTERVAL_MS=5000 bun dev"
  fi

  # Log capture warning
  if [[ -z "$CONVOS_SERVER_LOG" || ! -f "$CONVOS_SERVER_LOG" ]]; then
    warn "CONVOS_SERVER_LOG unset or missing. Phase 7 will warn-skip observability checks."
  fi
}

phase1_setup() {
  emit "## Phase 1 — setup"

  # AppCheck bypass via runtime config.
  emit "Flip AppCheck off for the demo run (UPSERT into RuntimeConfig)."
  emit_code "psql ... INSERT INTO \"RuntimeConfig\" ... ON CONFLICT DO UPDATE"
  psql_exec "
    INSERT INTO \"RuntimeConfig\" (key, value, \"updatedAt\")
    VALUES ('app_attest_enabled', 'false', now())
    ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, \"updatedAt\" = now();
  "
  _record_pass "phase1: app_attest_enabled UPSERT'd to false"

  # 30s runtime-config cache TTL — wait so the next request sees the new value.
  emit "Wait 32s for the in-memory runtime-config cache (30s TTL) to expire."
  emit_code "sleep 32"
  sleep 32
  _record_pass "phase1: runtime-config cache flushed"

  # Wipe auth-slice tables.
  emit "Wipe Account / AuthMethod / AuthNonce (CASCADE)."
  emit_code "psql ... TRUNCATE \"Account\", \"AuthMethod\", \"AuthNonce\" CASCADE"
  psql_exec 'TRUNCATE "AuthMethod", "Account", "AuthNonce" CASCADE'
  _record_pass "phase1: tables truncated"

  # Reset disabled-device state from prior demo runs.
  emit "Reset DeviceRegistration.disabled for demo-prefixed deviceIds."
  emit_code "psql ... UPDATE \"DeviceRegistration\" SET disabled=false WHERE \"deviceId\" LIKE '${DEMO_DEVICE_PREFIX}%'"
  psql_exec "UPDATE \"DeviceRegistration\" SET disabled = false WHERE \"deviceId\" LIKE '${DEMO_DEVICE_PREFIX}%'"
  _record_pass "phase1: demo device disabled-flag reset"

  emit "Tmp directory for cookie jars: \`$TMP\`."
}

phase2_happy_path() {
  emit "## Phase 2 — happy path"

  local jar="$TMP/cookies.happy.txt"

  # Step 1 — issue nonce.
  run_curl "Step 1 — issue nonce" \
    -X POST "$BASE_URL/api/v2/auth/nonce" \
    -c "$jar"
  assert_status "happy/nonce" 200 "$LAST_STATUS" || return 1

  # Step 2 — sign SIWE.
  local nonce
  nonce=$(extract_nonce_from_cookie_jar "$jar")
  assert_match "happy/nonce-shape" '^[a-f0-9]{64}$' "$nonce" || return 1

  emit "**Step 2 — sign SIWE off-line**"
  emit_code "bun run dev/scripts/sign-siwe.ts --nonce $nonce"
  local siwe_json
  siwe_json=$(bun run "$SCRIPT_DIR/sign-siwe.ts" --nonce "$nonce")
  emit_code_block "json" "$siwe_json"

  # Step 3 — exchange for JWT.
  local body
  body=$(jq -nc --argjson siwe "$siwe_json" --arg deviceId "${DEMO_DEVICE_PREFIX}dev-1" \
    '{deviceId: $deviceId, siwe: $siwe}')

  run_curl "Step 3 — exchange for JWT" \
    -X POST "$BASE_URL/api/v2/auth/token" \
    -b "$jar" \
    -H "Content-Type: application/json" \
    -d "$body"
  assert_status "happy/token" 200 "$LAST_STATUS" || return 1

  local jwt
  jwt=$(echo "$LAST_BODY" | jq -r '.token')
  emit "**JWT payload decoded:**"
  emit_code_block "json" "$(decode_jwt_payload "$jwt")"

  local account_id
  account_id=$(decode_jwt_payload "$jwt" | jq -r '.accountId')
  assert_match "happy/jwt-accountId-uuid" \
    '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' "$account_id" || return 1

  # Step 4 — probe /account-auth-check.
  run_curl "Step 4 — probe /account-auth-check" \
    -X GET "$BASE_URL/api/v2/account-auth-check" \
    -H "X-Convos-AuthToken: $jwt"
  assert_status "happy/account-auth-check" 200 "$LAST_STATUS" || return 1
  assert_json_eq "happy/account-auth-check-body" '.success' 'true' "$LAST_BODY" || return 1

  # Step 5 — probe /auth-check (legacy auth, no requireAccount).
  run_curl "Step 5 — probe /auth-check" \
    -X GET "$BASE_URL/api/v2/auth-check" \
    -H "X-Convos-AuthToken: $jwt"
  assert_status "happy/auth-check" 200 "$LAST_STATUS" || return 1

  # Step 6 — verify DB state.
  assert_psql_count "happy/account-count" "Account" 1 || return 1
  assert_psql_count "happy/auth-method-count" "AuthMethod" 1 || return 1
  assert_psql_count "happy/auth-nonce-count" "AuthNonce" 0 || return 1
}

phase3_negative_nonce_and_sig() {
  emit "## Phase 3 — negative SIWE matrix (nonce + signature)"

  local jar
  local device_id="${DEMO_DEVICE_PREFIX}neg-1"

  # --- replay: consume a nonce, then reuse the SAME cookie jar ---
  jar="$TMP/cookies.replay.txt"
  issue_nonce "$jar" || return 1
  # Snapshot the cookie BEFORE consumption (server will clear it on success).
  cp "$jar" "$TMP/cookies.replay.snapshot.txt"
  sign_and_token "replay/first-use" 200 "$jar" "$device_id" || return 1
  # Second use of the SAME (now-consumed) nonce — expect 401.
  sign_and_token "replay/second-use" 401 "$TMP/cookies.replay.snapshot.txt" "$device_id" || return 1

  # --- expired-nonce live exercise SKIPPED ---
  # Requires demo-side HMAC signing of an expired-but-valid-HMAC cookie.
  # Covered by tests/auth-nonce-repository.test.ts integration test.
  emit "**expired-nonce (live)** — skipped here, requires demo-side HMAC signing. Covered by tests/auth-nonce-repository.test.ts."
  SKIPPED_PHASES+=("phase3/expired-nonce-live")

  # --- HMAC tamper: edit one hex char of the cookie value ---
  jar="$TMP/cookies.hmac.txt"
  issue_nonce "$jar" || return 1
  # Flip the first char of the HMAC half (before the dot).
  awk 'BEGIN {OFS="\t"} $6 == "__Host-convos_nonce" {
    n = split($7, parts, ".");
    hmac = parts[1]; nonce = parts[2];
    c = substr(hmac, 1, 1);
    flipped = (c == "0") ? "1" : "0";
    hmac = flipped substr(hmac, 2);
    $7 = hmac "." nonce
  } { print }' "$jar" > "$jar.tampered"
  mv "$jar.tampered" "$jar"
  sign_and_token "hmac-tamper" 401 "$jar" "$device_id" || return 1

  # --- bad signature: signer key #2, address-override = key #1's address ---
  jar="$TMP/cookies.badsig.txt"
  issue_nonce "$jar" || return 1
  local key1_addr
  key1_addr=$(bun -e '
    import("viem/accounts").then(m => {
      console.log(m.privateKeyToAccount("0x" + "1".repeat(64)).address);
    });
  ')
  local key2_hex
  key2_hex="0x$(printf '2%.0s' $(seq 64))"
  sign_and_token "bad-signature" 401 "$jar" "$device_id" \
    --signer-key "$key2_hex" \
    --address-override "$key1_addr" || return 1
}

phase3_negative_siwe_fields() {
  emit "## Phase 3 — negative SIWE matrix (field mismatches)"

  local device_id="${DEMO_DEVICE_PREFIX}neg-2"
  local jar

  declare -a cases=(
    "domain-mismatch|--domain|evil.app"
    "uri-mismatch|--uri|https://evil.app"
    "chainid-not-allowed|--chain-id|137"
    "version-not-1|--tamper-version|2"
    "no-expiration|--no-expiration"
    "exp-too-far|--exp-offset|+11m"
    "exp-past|--exp-offset|-1m"
    "iat-skew|--iat-offset|-6m"
    "nbf-future|--nbf-offset|+1m"
  )

  for entry in "${cases[@]}"; do
    IFS="|" read -r -a parts <<< "$entry"
    local case_name="${parts[0]}"
    local signer_flags=("${parts[@]:1}")

    jar="$TMP/cookies.${case_name}.txt"
    issue_nonce "$jar" || continue
    sign_and_token "siwe-field/${case_name}" 401 "$jar" "$device_id" "${signer_flags[@]}" || true
  done
}

# --- main ---------------------------------------------------------------------

main() {
  TMP=$(mktemp -d /tmp/convos-auth-demo.XXXXXX)
  export TMP

  start_runbook
  phase0_preflight
  phase1_setup
  phase2_happy_path
  phase3_negative_nonce_and_sig
  phase3_negative_siwe_fields
}

main "$@"
