#!/usr/bin/env bash
# Local end-to-end auth demo.
# Spec: docs/superpowers/specs/2026-05-11-local-e2e-auth-demo-design.md
# Plan: docs/superpowers/plans/2026-05-11-local-e2e-auth-demo.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Config defaults — override via env.
: "${BASE_URL:=http://localhost:4000}"
: "${PSQL_URL:=postgres://postgres:convos@localhost:5432/postgres?sslmode=disable}"
: "${DEMO_DEVICE_PREFIX:=demo-}"
: "${CONTINUE_ON_FAIL:=0}"
: "${SELF_TEST:=0}"
: "${CONVOS_SERVER_LOG:=}"

export BASE_URL PSQL_URL

# Globals populated as we go.
PASSED_CASES=()
FAILED_CASES=()
SKIPPED_PHASES=()
RUNBOOK="$SCRIPT_DIR/AUTH.md"
TMP=""

# shellcheck source=lib/md.sh
source "$SCRIPT_DIR/lib/md.sh"
# shellcheck source=lib/psql.sh
source "$SCRIPT_DIR/lib/psql.sh"
# shellcheck source=lib/jwt.sh
source "$SCRIPT_DIR/lib/jwt.sh"
# shellcheck source=lib/http.sh
source "$SCRIPT_DIR/lib/http.sh"
# shellcheck source=lib/assert.sh
source "$SCRIPT_DIR/lib/assert.sh"

# --- exit/cleanup -------------------------------------------------------------

write_summary() {
  emit "## Summary"
  emit "Total cases: $((${#PASSED_CASES[@]} + ${#FAILED_CASES[@]}))"
  emit "Pass: ${#PASSED_CASES[@]}"
  emit "Fail: ${#FAILED_CASES[@]}"
  if [[ ${#SKIPPED_PHASES[@]} -gt 0 ]]; then
    emit "Skipped phases: ${SKIPPED_PHASES[*]}"
  fi
  if [[ ${#FAILED_CASES[@]} -gt 0 ]]; then
    emit "**Failures:**"
    for c in "${FAILED_CASES[@]}"; do
      emit "- $c"
    done
  fi
}

on_exit() {
  local code=$?
  write_summary || true
  if [[ -n "$TMP" && -d "$TMP" ]]; then
    rm -rf "$TMP"
  fi
  if [[ ${#FAILED_CASES[@]} -gt 0 ]]; then
    echo "❌ Demo finished with ${#FAILED_CASES[@]} failure(s)." >&2
    exit "${code:-1}"
  fi
  echo "✅ Demo finished. ${#PASSED_CASES[@]} case(s) passed." >&2
  exit 0
}
trap on_exit EXIT

# --- helpers ------------------------------------------------------------------

die() { echo "❌ preflight failed: $1" >&2; exit 1; }
warn() { echo "⚠️  $1" >&2; }

start_runbook() {
  cat > "$RUNBOOK" <<EOF
# Local end-to-end auth demo

Generated by \`dev/scripts/run-e2e-demo.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Branch: $(git -C "$REPO_ROOT" rev-parse --abbrev-ref HEAD) @ $(git -C "$REPO_ROOT" rev-parse --short HEAD).

## ⚠️ Side effects

- Wipes \`Account\`, \`AuthMethod\`, \`AuthNonce\` on every run.
- Flips \`RuntimeConfig.app_attest_enabled\` to \`false\` (demo asserts \`XMTP_ENV != production\` first).
- Modifies \`DeviceRegistration.disabled\` for deviceIds matching \`${DEMO_DEVICE_PREFIX}%\`.

## Prerequisites

- Postgres on localhost:5432 (\`./dev/up\`)
- Migrations applied (\`bun migrate:deploy\`)
- \`bun dev\` running on :4000 with \`SWEEP_INTERVAL_MS=5000\` and stdout tee'd to \`\$CONVOS_SERVER_LOG\`
- \`psql\`, \`jq\`, \`bun\` on PATH

EOF
}

# --- phases -------------------------------------------------------------------

phase0_preflight() {
  emit "## Phase 0 — preflight"

  # Production-safety guard
  if [[ "${XMTP_ENV:-}" == "production" ]]; then
    die "XMTP_ENV=production — refusing to run demo against production"
  fi

  # Postgres
  nc -z localhost 5432 || die "Postgres not reachable on :5432. Run ./dev/up first."
  _record_pass "Postgres reachable on :5432"

  # Server
  local code
  code=$(curl -sS -o /dev/null -w '%{http_code}' "$BASE_URL/api/v2/auth-check" || echo "000")
  if [[ "$code" != "401" ]]; then
    die "Server not responding correctly on $BASE_URL (got $code, expected 401 for missing token). Run 'bun dev' in another terminal."
  fi
  _record_pass "Server reachable on $BASE_URL (auth-check returned 401)"

  # Tools
  for tool in psql jq bun curl nc; do
    command -v "$tool" >/dev/null || die "$tool not on PATH"
  done
  _record_pass "psql, jq, bun, curl, nc on PATH"

  # Sweep interval warning
  if [[ -z "${SWEEP_INTERVAL_MS:-}" ]]; then
    warn "SWEEP_INTERVAL_MS not exported. Phase 6 will hang 10 min waiting for default sweep."
    warn "Recommended: SWEEP_INTERVAL_MS=5000 bun dev"
  fi

  # Log capture warning
  if [[ -z "$CONVOS_SERVER_LOG" || ! -f "$CONVOS_SERVER_LOG" ]]; then
    warn "CONVOS_SERVER_LOG unset or missing. Phase 7 will warn-skip observability checks."
  fi
}

# --- main ---------------------------------------------------------------------

main() {
  TMP=$(mktemp -d /tmp/convos-auth-demo.XXXXXX)
  export TMP

  start_runbook
  phase0_preflight

  # TODO subsequent tasks add phase1..phase7 here
}

main "$@"
