-- Seed the curated set of agent prompt hints: the 100 product-vetted ideas.
-- Idempotent: a row is inserted only when no existing hint already has the same
-- text, so re-running (or re-applying) this migration never duplicates. Ids are
-- gen_random_uuid(); timestamps are NOW(). All seeds are published with a stable
-- sortOrder (RAW listing order, 0..99) so the public endpoint returns them in a
-- deterministic order. Source: convos-assistants agent-ideas RAW list (prompt
-- strings only; the category grouping is a meaningless holdover and is dropped).
INSERT INTO "AgentPromptHint" ("id", "text", "published", "sortOrder", "createdAt", "updatedAt")
SELECT gen_random_uuid(), v."text", true, v."sortOrder", NOW(), NOW()
FROM (
    VALUES
        ('A trip planner for the group chat', 0),
        ('A bachelorette-weekend RSVP wrangler', 1),
        ('A birthday-trip planner that books one a year', 2),
        ('A trip coordinator for the college crew', 3),
        ('A family-vacation planner that herds the logistics', 4),
        ('A weekend-cabin scout for date weekends', 5),
        ('A mom-and-me trip planner', 6),
        ('A road-trip planner that maps the long way home', 7),
        ('An anniversary-trip planner that never forgets the year', 8),
        ('A winter-getaway scout that flags cheap flights', 9),
        ('A family-dinner whip', 10),
        ('A weekly state-of-the-union for couples', 11),
        ('A care coordinator for siblings sharing mom''s care', 12),
        ('A chore-rotation referee', 13),
        ('A carpool coordinator that herds the parents', 14),
        ('A school-week runner for the kid', 15),
        ('A weekend-babysitting wrangler', 16),
        ('A shared-calendar nudge for date night', 17),
        ('A holiday planner for the whole family', 18),
        ('A household manager that keeps two heads in sync', 19),
        ('A Friday-night planner for the group chat', 20),
        ('A nudge that puts my friends back on the calendar', 21),
        ('A hangout fixer when nobody can decide', 22),
        ('A party planner that books a season-opener', 23),
        ('A scheduler that finds the rare date everyone agrees on', 24),
        ('A keep-in-touch agent for old friends', 25),
        ('A reconnect agent for friends I owe a text', 26),
        ('A spot picker for our standing friend dinner', 27),
        ('A dinner-party concierge', 28),
        ('A weekend-hike captain for the group', 29),
        ('A run coach that keeps the streak alive', 30),
        ('A 75 Hard pod runner with the gang', 31),
        ('A weekly workout planner', 32),
        ('A fitness-buddy matchmaker', 33),
        ('A half-marathon coach', 34),
        ('A workout tracker that catches the slacking', 35),
        ('A gym-skip blocker', 36),
        ('A daily fitness check-in', 37),
        ('A monthly movement-challenge', 38),
        ('A coach for the gym group chat', 39),
        ('A reading coach with a monthly nudge', 40),
        ('A book-club whip for the group', 41),
        ('A yearly reading planner', 42),
        ('A pre-trip book picker', 43),
        ('A reading agent that finishes what I start', 44),
        ('A yearly reading-challenge runner', 45),
        ('A book recommender that learns my taste', 46),
        ('A Spanish practice partner', 47),
        ('A daily Duolingo nudge', 48),
        ('A podcast curator for the commute', 49),
        ('A monthly savings nudge', 50),
        ('A bill-splitter for the group chat', 51),
        ('A no-spend-month coach', 52),
        ('A daily spending tracker', 53),
        ('A roommate settle-up agent', 54),
        ('A monthly budget runner', 55),
        ('A credit-card payoff coach', 56),
        ('A savings-challenge runner with the group', 57),
        ('A group-trip treasurer', 58),
        ('An overspending flagger every month', 59),
        ('A morning wake-up coach', 60),
        ('A morning-routine runner', 61),
        ('A daily water-intake tracker', 62),
        ('A meditation-streak keeper', 63),
        ('A morning check-in agent', 64),
        ('A quarterly-goals coach', 65),
        ('An anti-doomscroll nudge', 66),
        ('A Sunday weekly-review host', 67),
        ('A journaling habit-keeper', 68),
        ('A Sunday parent-call reminder', 69),
        ('A nightly what-to-cook coach', 70),
        ('A weekly meal planner', 71),
        ('A cook-for-your-partner coach', 72),
        ('A recipe builder from what''s in the fridge', 73),
        ('A Sunday meal-prep runner', 74),
        ('A cookbook recommender', 75),
        ('A dinner planner that handles every diet', 76),
        ('A weekly try-something-new cooking coach', 77),
        ('A weekly grocery-list builder', 78),
        ('A ''cook at home'' nudge', 79),
        ('A kids'' birthday-party planner', 80),
        ('A milestone-birthday planner going forward', 81),
        ('A baby-shower planner for friends', 82),
        ('A Friendsgiving coordinator every year', 83),
        ('A standing dinner-party host', 84),
        ('A surprise planner that doesn''t spoil it', 85),
        ('A backyard movie-night runner', 86),
        ('A venue scout for big events', 87),
        ('An anniversary-dinner planner every year', 88),
        ('A fantasy-league commissioner', 89),
        ('A Sunday weekly planner', 90),
        ('A prioritization coach for overwhelmed days', 91),
        ('A thank-you-notes nudge', 92),
        ('A solo-weekend curator', 93),
        ('A card-writer reminder for birthdays I miss', 94),
        ('A rest-day planner', 95),
        ('A weekly self-check-in', 96),
        ('A weekend planner when I can''t decide', 97),
        ('A weekly meeting-prep coach', 98),
        ('A daily self-check-in', 99)
) AS v ("text", "sortOrder")
WHERE NOT EXISTS (
    SELECT 1 FROM "AgentPromptHint" h WHERE h."text" = v."text"
);
