name: Validate code quality

on:
  push:
    branches:
      - main
      - dev

  pull_request:

jobs:
  check:
    name: Typecheck, format check, lint
    runs-on: warp-ubuntu-latest-x64-8x
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"
      - run: bun install
      - run: bun check
      - run: ./dev/up
        env:
          NOTIFICATION_DELIVERY_URL: ${{ secrets.NOTIFICATION_DELIVERY_URL }}
      - run: sleep 5s
      - run: bun migrate:dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: bun test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XMTP_ENV: local
          SCALEWAY_ACCESS_KEY_ID: ${{ secrets.SCALEWAY_ACCESS_KEY_ID }}
          SCALEWAY_SECRET_KEY_ID: ${{ secrets.SCALEWAY_SECRET_KEY_ID }}
          SCALEWAY_ATTACHMENTS_BUCKET: ${{ secrets.SCALEWAY_ATTACHMENTS_BUCKET }}
          NOTIFICATION_SERVER_URL: ${{ secrets.NOTIFICATION_SERVER_URL }}
          NOTIFICATION_DELIVERY_URL: ${{ secrets.NOTIFICATION_DELIVERY_URL }}
