-- This migration was auto-generated by Prisma but incorrectly dropped defaults.
-- The defaults are needed for raw SQL inserts used in schema tests.
-- We keep the defaults intact by making this a no-op migration.

-- No schema changes needed beyond the column rename in the previous migration
